services:

  # ─────────────────────────────────────────────
  # AUTH SERVICE
  # localhost:3030  →  container:8080
  # ─────────────────────────────────────────────
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - '3030:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-red-morning-b4ng7s53-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_XD7MNR4ClvjK
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

  # ─────────────────────────────────────────────
  # OWNER REQUEST SERVICE
  # localhost:3031  →  container:8081
  # ─────────────────────────────────────────────
  owner-request-service:
    build:
      context: ./owner-request-service
      dockerfile: Dockerfile
    ports:
      - '3031:8081'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-red-morning-b4ng7s53-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_XD7MNR4ClvjK
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

  # ─────────────────────────────────────────────
  # OWNER DOCUMENT SERVICE
  # localhost:3032  →  container:8082
  # ─────────────────────────────────────────────
  owner-document-service:
    build:
      context: ./owner-document-service/owner-document-service
      dockerfile: Dockerfile
    ports:
      - '3032:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-red-morning-b4ng7s53-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_XD7MNR4ClvjK
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - CLOUDINARY_CLOUD_NAME=dblawr8bm
      - CLOUDINARY_API_KEY=914174568446748
      - CLOUDINARY_API_SECRET=p2dCGEBFNQ85g4vUzjr6AvNWtQ8

  # ─────────────────────────────────────────────
  # LOCATION SERVICE (Countries, States, Cities)
  # localhost:3035  →  container:8085
  # ─────────────────────────────────────────────
  location-service:
    build:
      context: ./location-service
      dockerfile: Dockerfile
    ports:
      - '3035:8085'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-red-morning-b4ng7s53-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_XD7MNR4ClvjK
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

  # ─────────────────────────────────────────────
  # CATEGORY SERVICE
  # localhost:3036  →  container:8086
  # ─────────────────────────────────────────────
  category-service:
    build:
      context: ./category-service
      dockerfile: Dockerfile
    ports:
      - '3036:8086'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-red-morning-b4ng7s53-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_XD7MNR4ClvjK
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver

  # ─────────────────────────────────────────────
  # VENUE SERVICE
  # localhost:3037  →  container:8087
  # ─────────────────────────────────────────────
  venue-service:
    build:
      context: ./venue-service
      dockerfile: Dockerfile
    ports:
      - '3037:8087'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-red-morning-b4ng7s53-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_XD7MNR4ClvjK
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - CLOUDINARY_CLOUD_NAME=dblawr8bm
      - CLOUDINARY_API_KEY=914174568446748
      - CLOUDINARY_API_SECRET=p2dCGEBFNQ85g4vUzjr6AvNWtQ8

  # ─────────────────────────────────────────────
  # COURT SERVICE
  # localhost:3038  →  container:8088
  # ─────────────────────────────────────────────
  court-service:
    build:
      context: ./court-service
      dockerfile: Dockerfile
    ports:
      - '3038:8088'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-red-morning-b4ng7s53-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_XD7MNR4ClvjK
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - CLOUDINARY_CLOUD_NAME=dblawr8bm
      - CLOUDINARY_API_KEY=914174568446748
      - CLOUDINARY_API_SECRET=p2dCGEBFNQ85g4vUzjr6AvNWtQ8

  # ─────────────────────────────────────────────
  # STAFF SERVICE
  # localhost:3039  →  container:8089
  # ─────────────────────────────────────────────
  staff-service:
    build:
      context: ./staff-service
      dockerfile: Dockerfile
    ports:
      - '3039:8089'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-red-morning-b4ng7s53-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_XD7MNR4ClvjK
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
