spring.application.name=owner-verification
server.port=${SERVER_PORT:8081}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-red-morning-b4ng7s53-pooler.c-6.us-east-2.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_XD7MNR4ClvjK}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dblawr8bm}
cloudinary.api-key=${CLOUDINARY_API_KEY:914174568446748}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:p2dCGEBFNQ85g4vUzjr6AvNWtQ8}